name: Deploy Databricks Notebooks

on:
  push:
    paths:
      - 'notebooks/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy notebooks (bronze/silver/gold)
        run: |
          databricks workspace import_dir ./notebooks/bronze /Projects/HealthcareFIN/bronze --overwrite
          databricks workspace import_dir ./notebooks/silver /Projects/HealthcareFIN/silver --overwrite
          databricks workspace import_dir ./notebooks/gold /Projects/HealthcareFIN/gold --overwrite
